### ISSUE TITLE
Error: No connection to FCU

### ISSUE THREAD

**Issue by shourez** [CopterExpress/clover#485]
The same PC as in https://github.com/CopterExpress/clover/issues/484.

In VM, block programming interface doesn't connect to Gazebo
![No connection to FCU](https://user-images.githubusercontent.com/95218252/222981067-755b647a-766f-48f7-91e3-cca71afd6fa8.png)

**Comment by okalachev** [comment]
Can you please provide the full launch command output, from the terminal?

**Comment by shourez** [comment]
Here it is

[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 192.168.238.129
[ INFO] [1678127390.344030690]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1678127390.351515672]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 192.168.238.129
[Msg] Loading world file [/home/clover/catkin_ws/src/clover/clover_simulation/resources/worlds/clover_aruco.world]
[ INFO] [1678127391.916267973]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[INFO] [1678127391.973745, 0.000000]: wait_for_service(/gazebo/spawn_urdf_model): finally were able to contact [rosrpc://clover-dev:35257]
[INFO] [1678127391.986251, 0.000000]: Calling service /gazebo/spawn_urdf_model
[INFO] [1678127392.989377, 0.004000]: Spawn status: SpawnModel: Successfully spawned entity
[ INFO] [1678127393.105277662, 0.004000000]: Physics dynamic reconfigure ready.
[spawn_clover_dev_3051_7709871114269057712-4] process has finished cleanly
log file: /home/clover/.ros/log/382a859e-bc4b-11ed-a7bf-93a94191dd8e/spawn_clover_dev_3051_7709871114269057712-4*.log
[ INFO] [1678127394.532303295, 0.004000000]: Camera Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1678127394.567942426, 0.004000000]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
[Msg] Connecting to PX4 SITL using TCP
[Msg] Lockstep is enabled
[Msg] Speed factor set to: 1
[ INFO] [1678127395.738227341, 0.004000000]: LedController has started (as server) in namespace ''
[Wrn] [gazebo_mavlink_interface.cpp:152] No identifier on joint. Using 0 as default sensor ID
[Msg] Using MAVLink protocol v2.0
INFO  [simulator] Simulator connected on TCP port 4560.
[ INFO] [1678127395.983872749, 0.004000000]: Initialize LED Controller
[ INFO] [1678127396.007141743, 0.008000000]: ros.roscpp: waitForService: Service [/led/set_leds] is now available.
[ INFO] [1678127396.261686602, 0.044000000]: ros.clover: ready
INFO  [commander] LED: open /dev/led0 failed (22)
* PWM_AUX_OUT: curr: 0 -> new: 1234
* PWM_MAIN_OUT: curr: 0 -> new: 1234
Illegal instruction (core dumped)
[gazebo-1] process has died [pid 3068, exit code 132, cmd /opt/ros/noetic/lib/gazebo_ros/gzserver --verbose -e ode /home/clover/catkin_ws/src/clover/clover_simulation/resources/worlds/clover_aruco.world __name:=gazebo __log:=/home/clover/.ros/log/382a859e-bc4b-11ed-a7bf-93a94191dd8e/gazebo-1.log].
log file: /home/clover/.ros/log/382a859e-bc4b-11ed-a7bf-93a94191dd8e/gazebo-1*.log
[Err] [Visual.cc:410] Service call [/shininess] timed out
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual].
[ INFO] [1678127401.923273320, 0.084000000]: LedController has started (as client) in namespace ''
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_1].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_2].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_3].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_4].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_5].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_6].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_7].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_8].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_9].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_10].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_11].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_12].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_13].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_14].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_15].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_16].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_17].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_18].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_19].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_20].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_21].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_22].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_23].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_24].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_25].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_26].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_27].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_28].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_29].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_30].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_31].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_32].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_33].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_34].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_35].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_36].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_37].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_38].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_39].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_40].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_41].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_42].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_43].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_44].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_45].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_46].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_47].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_48].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_49].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_50].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_51].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_52].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_53].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_54].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_55].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_56].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::led_link::led_link_visual_57].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_0].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_1].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_2].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_3].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_4].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_5].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_6].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_7].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_8].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_9].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_10].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_11].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_12].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_13].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_14].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_15].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_16].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_18].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_19].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_20].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_21].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_22].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_23].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_24].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_25].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_26].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_27].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_28].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_29].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_30].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_31].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_32].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_33].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_34].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_35].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_36].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_37].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_38].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_39].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_40].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_41].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_42].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_43].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_44].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_45].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_46].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_47].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_48].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_49].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_50].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_51].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_52].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_53].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_54].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_55].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_56].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_57].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_58].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_59].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_60].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_61].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_62].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_63].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_64].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_65].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_66].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_67].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_68].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_69].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_70].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_71].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_72].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_73].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_74].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_75].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_76].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_77].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_78].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_79].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_80].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_81].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_82].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_83].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_84].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_85].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_86].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_87].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_88].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_89].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_90].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_91].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_92].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_93].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_94].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_95].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_96].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_97].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_98].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [aruco_2_99::aruco_2_99_link::visual_marker_2_99].
[Err] [Visual.cc:383] Service name [/shininess] not advertised, not attempting to load shininess for visual with name [clover::base_guard_link::base_guard_link_visual].
[Wrn] [ColladaLoader.cc:1928] Triangle input semantic: 'COLOR' is currently not supported
[Wrn] [ColladaLoader.cc:1928] Triangle input semantic: 'COLOR' is currently not supported
[Wrn] [ColladaLoader.cc:1928] Triangle input semantic: 'COLOR' is currently not supported
[Wrn] [ColladaLoader.cc:1928] Triangle input semantic: 'COLOR' is currently not supported
[Wrn] [Publisher.cc:135] Queue limit reached for topic /gazebo/default/user_camera/pose, deleting message. This warning is printed only once.
2023-03-06 21:30:43+0300 [-] [INFO] [1678127443.736497, 0.092000]: rosout: Client connected.  1 clients total.
2023-03-06 21:30:49+0300 [-] [INFO] [1678127449.410785, 0.092000]: rosout: [Client 0] Subscribed to /clover_blocks/block
2023-03-06 21:30:49+0300 [-] [INFO] [1678127449.490824, 0.092000]: rosout: [Client 0] Subscribed to /clover_blocks/running
2023-03-06 21:30:49+0300 [-] [INFO] [1678127449.643627, 0.092000]: rosout: [Client 0] Subscribed to /clover_blocks/print
2023-03-06 21:30:49+0300 [-] [INFO] [1678127449.712124, 0.092000]: rosout: [Client 0] Subscribed to /clover_blocks/error
2023-03-06 21:30:49+0300 [-] [INFO] [1678127449.783937, 0.092000]: rosout: [Client 0] Subscribed to /clover_blocks/prompt
[INFO] [1678127449.857143, 0.092000]: rosout: Run program
[ INFO] [1678127449.932253728, 0.092000000]: ros.clover: State timeout, check mavros settings
[ERROR] [1678127449.935620, 0.092000]: rosout: State timeout, check mavros settings
Traceback (most recent call last):
  File "/home/clover/catkin_ws/src/clover/clover_blocks/src/clover_blocks", line 115, in program_thread
    exec(req.code, g)
  File "<string>", line 31, in <module>
  File "<string>", line 16, in navigate_wait
Exception: State timeout, check mavros settings
[INFO] [1678127449.951451, 0.092000]: rosout: Program terminated

**Comment by okalachev** [comment]
So you got the same errors in the [VM image](https://clover.coex.tech/en/simulation_vm.html) and after the [manual installation](https://clover.coex.tech/en/simulation_native.html)?

**Comment by shourez** [comment]
> So you got the same errors in the [VM image](https://clover.coex.tech/en/simulation_vm.html) and after the [manual installation](https://clover.coex.tech/en/simulation_native.html)?

Looks so. But VM at least starts Gazebo, while manual installation doesn't do even that. It may be somehow connected to hardware.

**Comment by okalachev** [comment]
Closed as stale.
